### ISSUE TITLE
Dojox 404 error reported in MS4W 2.8 package

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#104]
Not sure if it is just me, but firebug is reporting:
```
404 Not Found The requested URL "/geomoose2/build/dojox/grid/DataGrid.js" was not found on this server.
```
On initial page load of a clean install of the Geomoose 2.8 demo for MS4W. Not sure what the missing file does as everything is testing just fine, but still...

**Comment by tchaddad** [comment]
Hmm, well adding this missing file seems to just trigger additional calls to missing files, and prevents GeoMoose from fully loading, so leaving the file out seems to be the correct thing to do. Just not sure why it is being called in the first place...

**Comment by klassenjs** [comment]
I know you said otherwise, but I suspect it might be an extension is trying
to use DataGrid (Used to display tables with Dojo/Dijit).  I don't think
that is used in GeoMoose core.

Missing and looking for it usually means that the dojo.requires
dependencies are not set correctly at build time.  This could especially be
a problem if an extension uses Dojo but is declared and defined in the
traditional GeoMoose way (OpenLayers class included in geomoose.html) vs
the Dojo way (dojo class/requires/provides, and included in
site/includes.js)

**Comment by tchaddad** [comment]
I'll double check if any particular extensions were the cause. AFAIK, I was testing with only a few minor ones turned on (bookmark, attribution...).

**Comment by theduckylittle** [comment]
I am not seeing this behaviour in master.

I did some power grepping through the code but I haven't been able to find a reference to DataGrid.  Can anyone else verify?

**Comment by elil** [comment]
@tchaddad would this be in firebug under console-->errors?  Any particular "show" settings?  I didn't find anything there.  I also checked the Apache access and error logs and didn't find datagrid there.

**Comment by tchaddad** [comment]
Ok, this is my mistake - it seems the triggered warning was coming from a loaded extension that I didn't realize was being referenced in my index.html 

	<script type="text/javascript" src="extensions/SelectTools.js"></script>

So that means this Issue can be closed as it relates to the Demo itself. 

@elil is this an extension from Oregon GeoMoose by any chance?
