### ISSUE TITLE
WFS-T filter throws error on construction

### ISSUE THREAD

**Issue by brentfraser** [geomoose/geomoose#140]
In WFS.js (trunk), the preParseNode function calls this.updateFilter which references this._ol_layer.  The object this._ol_layer does not yet exist and the code fails.

**Comment by brentfraser** [comment]
Test by adding
`<filter type="cql"><![CDATA[geoid10 = 2746924]]></filter>`
to the "census_cities" mapsource.

The above filter should result in showing only the Northfield city outline.

**Comment by brentfraser** [comment]
To get around the problem, my original prototype had some code in Vector.js, line 266:
`        // BWF (Add feature filtering): CQL filter to restrict features sent from server
        var filter_tag = mapbook_entry.getElementsByTagName('filter');
        if (filter_tag) {
            var filter_text = OpenLayers.Util.getXmlNodeValue(filter_tag[0]);
            var filter = new OpenLayers.Filter.Logical();
            var format_CQL = new OpenLayers.Format.CQL();
            try {
                filter = format_CQL.read(filter_text);
            } catch (err) {
                GeoMOOSE.error('OpenLayers CQL parser is unable to parse:'+filter_text);
            }
            if (filter) {
                this.filter = filter;
            }
        }
`

**Comment by theduckylittle** [comment]
I see what I did really wrong here...

preParseNode is being used like the constructor instead of what it was intended to do (transform the XML before it's actually parsed).  I moved the filter code into the actual constructor, which in the chain of inheritance is called after _ol_layer is created.  

Works like a charm now.  I tested with the Northfield CQL example above.

**Comment by brentfraser** [comment]
Fix tested.
