### ISSUE TITLE
group_checkboxes removed?

### ISSUE THREAD

**Issue by federicogodan** [geomoose/geomoose#160]
In previous versions of theres a param called group_checkboxes, in the docs says "Allow entire groups to be toggled on or off with a global checkbox. Defaults to true."

The code for group_checkboxes is commented in Catalog.js and so, its not working at the moment, why it was removed from the present releases?

**Comment by elil** [comment]
Were group_checkboxes previously working?  If so, how is the config the same or different?

If you're referring to this specific [code](https://github.com/geomoose/geomoose-js/blob/master/geomoose/GeoMOOSE/Tab/Catalog.js#L368), it has been commented since [2011] (https://trac.osgeo.org/geomoose/changeset/476/).

How to enable group_checkboxes might be better discussed on the email list.  Does mapbook.xml have something like:

`<configuration>
...
		<param name="group_checkboxes">true</param>
...
</configuration>` ?

**Comment by federicogodan** [comment]
Yes, i'm referring to that code.

I add group_checkboxes to mapbook.xml but has no effect on the app.

I found a old questions about that in the mailing lists but is not aswered yet:
http://osgeo-org.1560.x6.nabble.com/Geomoose-users-group-checkbox-and-legend-icon-td5181092.html

**Comment by theduckylittle** [comment]
Group checkboxes were problematic.  Specifically when someone was trying to turn on or off individual layers in the group, the checkbox could be found to be checked when not all the layers were checked, or exactly the opposite.  So the state could get very odd and show bugs.  Past that, it was quite a few years ago since we had support for the feature, so I don't remember all of the reasons for it.

**Comment by elil** [comment]
This is an option to remove group_checkboxes from code, demo, and docs.  Can you review these?

**Comment by theduckylittle** [comment]
Wow, this is like the best Issue ever.  Someone reports bug, someone fixes bug with pull requests.  YAY!
