### ISSUE TITLE
Search with one result zooms to incorrect area

### ISSUE THREAD

**Issue by elil** [geomoose/geomoose#90]
While looking at #84, I ran into another issue.

Search PIN for 130220003076.  You get one results and it zooms to 40.479, 4.343.  Search for 130220003 you get two results and there is not a zoom to the wrong location.

**Comment by theduckylittle** [comment]
This was a projections problem.  It's odd we only caught it now  because the code was quite old.  Here's what happened:

1. When only returning one result we had a feature to zoom directly to that result.  However, query.php  was returning the coordinates to that result in the dataset's projection.  This was causing the map to zoom to an incorrect extent when the mapping projection and the data's projection were different.
2. GeoMOOSE.zoomToExtent did not support reprojection.  

The fix:
1. That seeded result is now returned in the EPSG:4326.
2. zoomToExtent was updated to allow for projections to be specified.

**Comment by elil** [comment]
Works correctly in the demo.
