### ISSUE TITLE
Add display of number of selected results to Select Template output

### ISSUE THREAD

**Issue by tchaddad** [geomoose/geomoose#93]
As suggested in this thread:

http://osgeo-org.1560.x6.nabble.com/Geomoose-users-Number-of-identify-results-td5215718.html

**Comment by elil** [comment]
Not sure where this reply will land (Tanya?  The ticket?).


On Wed, Jul 15, 2015 at 2:47 PM, TC Haddad <notifications@github.com> wrote:

> As suggested in this thread:
>
>
> http://osgeo-org.1560.x6.nabble.com/Geomoose-users-Number-of-identify-results-td5215718.html
>

I try to link to the OSGeo list since it is a stable url (and doesn't have
ads).

https://lists.osgeo.org/pipermail/geomoose-users/2015-July/005705.html

Eli

**Comment by tchaddad** [comment]
Both!

**Comment by theduckylittle** [comment]
Yay!

Not sure I'll sneak this into 2.8.  Once testing is wrapped, then I really
want to drop a release.

**Comment by tchaddad** [comment]
Yes, I deliberately left off milestone - your choice on that one...

**Comment by theduckylittle** [comment]
This actually works in 2.9 development.

**Comment by tchaddad** [comment]
Yes - working for me in 97b9ce2
